In [1]:
!pip install word2number

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import linear_model
from word2number import w2n

In [2]:
df = pd.read_csv('hiring.csv')
df
df.dtypes

experience          object
test_score         float64
interview_score      int64
salary               int64
dtype: object

In [3]:
df.experience.fillna('zero',inplace=True)

df.experience

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [4]:
df['experience'] = df['experience'].astype(str)

In [5]:
df.dtypes


experience          object
test_score         float64
interview_score      int64
salary               int64
dtype: object

In [6]:
df.experience = df.experience.apply(w2n.word_to_num) 


In [7]:
median_test_score = df['test_score'].median()
df['test_score'].fillna(median_test_score,inplace=True)
df.dtypes

experience           int64
test_score         float64
interview_score      int64
salary               int64
dtype: object

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df['salary'])

LinearRegression()

In [9]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [10]:
reg.intercept_

17737.263464337688

In [11]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [12]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [13]:
2812.95487627*2 + 1845.70596798*9.0 + 2205.24017467*6 + 17737.263464337688

53205.96797671769